#!/bin/bash
# LazyCat App Publisher - Build Script for SRK Toolbox
# Generated by lazycat-app-publisher skill

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check required files
check_files() {
    print_info "检查必需文件..."
    if [[ ! -f "lzc-manifest.yml" ]]; then
        print_error "缺少 lzc-manifest.yml"
        exit 1
    fi
    if [[ ! -f "lzc-build.yml" ]]; then
        print_error "缺少 lzc-build.yml"
        exit 1
    fi
    if [[ ! -f "icon.png" ]]; then
        print_warning "缺少 icon.png，将使用默认图标"
    fi
    print_success "文件检查完成"
}

# Show app info
show_info() {
    print_info "=== SRK Toolbox 应用信息 ==="
    if [[ -f "lzc-manifest.yml" ]]; then
        echo ""
        echo "📦 配置: lzc-manifest.yml"
        grep -E "^name:|^package:|^version:|^description:" lzc-manifest.yml | head -5
    fi
    echo ""
    echo "📋 参数说明:"
    echo "   - 无需用户配置的参数（简单应用）"
    echo ""
}

# Build app
build_app() {
    print_info "构建应用..."
    check_files
    lzc-cli project build -o srk-toolbox-$(date +%Y%m%d).lpk
    print_success "构建完成!"
}

# Copy image to LazyCat registry
copy_image() {
    print_info "复制镜像到懒猫仓库..."
    if ! lzc-cli appstore my-images &> /dev/null 2>&1; then
        print_warning "未登录懒猫应用商店"
        print_info "请先执行: lzc-cli appstore login"
        return 1
    fi

    # Get image from manifest
    IMAGE=$(grep "image:" lzc-manifest.yml | head -1 | awk '{print $2}')
    print_info "镜像: $IMAGE"

    result=$(lzc-cli appstore copy-image "$IMAGE" 2>&1)
    echo "$result"

    if echo "$result" | grep -q "uploaded:"; then
        NEW_IMAGE=$(echo "$result" | grep "^uploaded:" | awk '{print $2}')
        print_success "镜像已更新: $NEW_IMAGE"

        # Update manifest
        sed -i "s|image: $IMAGE|image: $NEW_IMAGE # $IMAGE|" lzc-manifest.yml
        print_info "已更新 lzc-manifest.yml"

        # Rebuild
        build_app
    else
        print_warning "镜像复制失败或已取消"
    fi
}

# Publish app
publish_app() {
    print_info "发布应用到商店..."
    if ! lzc-cli appstore my-images &> /dev/null 2>&1; then
        print_warning "未登录懒猫应用商店"
        print_info "请先执行: lzc-cli appstore login"
        return 1
    fi

    LPK=$(ls -t *.lpk 2>/dev/null | head -1)
    if [[ -z "$LPK" ]]; then
        print_error "未找到 .lpk 文件，请先构建"
        return 1
    fi

    print_info "发布: $LPK"
    lzc-cli appstore publish "$LPK"
    print_success "发布完成!"
}

# One-click publish
one_click_publish() {
    print_info "=== 一键发布流程 ==="
    echo ""

    echo "阶段 1: 初始构建"
    build_app
    echo ""

    echo "阶段 2: 镜像复制"
    copy_image
    echo ""

    echo "阶段 3: 发布审核"
    publish_app
    echo ""

    print_success "全部完成!"
}

# Main menu
main() {
    echo ""
    echo "========================================"
    echo "   SRK Toolbox - LazyCat 应用发布工具"
    echo "========================================"
    echo ""
    echo "1. 📦 构建应用 (Build)"
    echo "2. 🔧 镜像复制到懒猫仓库 (Copy Image)"
    echo "3. 📤 发布到应用商店 (Publish)"
    echo "4. 🚀 一键构建+镜像复制+发布 (One-Click)"
    echo "5. 📋 查看应用信息 (Info)"
    echo "6. ❌ 退出"
    echo ""

    read -p "请选择操作 [1-6]: " choice
    echo ""

    case $choice in
        1) build_app ;;
        2) copy_image ;;
        3) publish_app ;;
        4) one_click_publish ;;
        5) show_info ;;
        6) exit 0 ;;
        *) print_error "无效选择" ;;
    esac
}

main "$@"
